[2024-12-22 14:12:54,247] root - INFO - >>>> stage Data ingestion pipeline started <<<<<
[2024-12-22 14:12:54,251] root - INFO - created dir at :artifacts
[2024-12-22 14:12:54,251] root - INFO - created dir at :artifacts/data_ingestion
[2024-12-22 14:12:54,251] root - INFO - Downloading data from https://drive.google.com/file/d/1J8Gd0d4YwOhdkN0SALD1CBRe-argMey_/view?usp=drive_link into file artifacts/data_ingestion/data.zip
[2024-12-22 14:12:54,264] urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): drive.google.com:443
[2024-12-22 14:12:59,012] urllib3.connectionpool - DEBUG - https://drive.google.com:443 "GET /uc?/export=download&id=1J8Gd0d4YwOhdkN0SALD1CBRe-argMey_ HTTP/11" 303 0
[2024-12-22 14:12:59,012] urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): doc-00-3o-docs.googleusercontent.com:443
[2024-12-22 14:13:00,755] urllib3.connectionpool - DEBUG - https://doc-00-3o-docs.googleusercontent.com:443 "GET /docs/securesc/u727qbb4h4vr5rmirulce2ubr3lm7ml6/96o8rgqkbls7m2baqadcf4p9itr90i90/1734856950000/05840176216229665370/06160806390192916552Z/1J8Gd0d4YwOhdkN0SALD1CBRe-argMey_?uuid=8e08f4c1-67fe-4548-849b-7a751fc3375c HTTP/11" 302 0
[2024-12-22 14:13:01,330] urllib3.connectionpool - DEBUG - https://drive.google.com:443 "GET /nonceSigner?nonce=85gnl4t6ddvtk&continue=https://doc-00-3o-docs.googleusercontent.com/docs/securesc/u727qbb4h4vr5rmirulce2ubr3lm7ml6/96o8rgqkbls7m2baqadcf4p9itr90i90/1734856950000/05840176216229665370/06160806390192916552Z/1J8Gd0d4YwOhdkN0SALD1CBRe-argMey_?uuid%3D8e08f4c1-67fe-4548-849b-7a751fc3375c&hash=tgd7bg1p29gd512ucl8gvvnvioovphm7 HTTP/11" 302 0
[2024-12-22 14:13:04,265] urllib3.connectionpool - DEBUG - https://doc-00-3o-docs.googleusercontent.com:443 "GET /docs/securesc/u727qbb4h4vr5rmirulce2ubr3lm7ml6/96o8rgqkbls7m2baqadcf4p9itr90i90/1734856950000/05840176216229665370/06160806390192916552Z/1J8Gd0d4YwOhdkN0SALD1CBRe-argMey_?uuid=8e08f4c1-67fe-4548-849b-7a751fc3375c&nonce=85gnl4t6ddvtk&user=06160806390192916552Z&hash=jtt4reutqsuha11p1ri4m3tk2lkkr4qo HTTP/11" 200 2323493
[2024-12-22 14:13:06,230] root - ERROR - name 'logger' is not defined
Traceback (most recent call last):
  File "D:\ML_Projects\End_to_end\Text_Classification\main.py", line 10, in <module>
    obj.main()
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\pipeline\data_ingestion.py", line 23, in main
    raise e
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\pipeline\data_ingestion.py", line 18, in main
    data_ingestion.download_file()
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\components\data_ingestion.py", line 26, in download_file
    raise e
  File "D:\ML_Projects\End_to_end\Text_Classification\hate\components\data_ingestion.py", line 24, in download_file
    logger.info(f"Downloading data from {dataset_url} into file {zip_download_dir}")
    ^^^^^^
NameError: name 'logger' is not defined
